terraform_version = "1.14.3"

[public_repo]
directory = "./sandbox"
repo      = "pabardina-clinia/byo-eks-postgrest"
branch    = "main"

[vars]
cluster_name             = "{{.nuon.install.inputs.cluster_name}}"
namespace                = "{{.nuon.install.inputs.namespace}}"
aws_region               = "{{.nuon.install.sandbox.account.region}}"
provision_iam_role_arn   = "{{.nuon.install_stack.outputs.provision_iam_role_arn}}"
maintenance_iam_role_arn = "{{.nuon.install_stack.outputs.maintenance_iam_role_arn}}"
deprovision_iam_role_arn = "{{.nuon.install_stack.outputs.deprovision_iam_role_arn}}"
nuon_install_id          = "{{.nuon.install.id}}"
