type        = "aws-cloudformation"
name        = "nuon-byo-eks-postgrest-{{.nuon.install.id}}"
description = "BYO EKS runner for PostgREST + CNPG: Install {{.nuon.install.id}}"

vpc_nested_template_url    = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.4.0/byo-vpc/default/stack.yaml"
runner_nested_template_url = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.4.0/runner/asg/stack.yaml"

[[custom_nested_stacks]]
name         = "runner_sg_eks_access"
template_url = "https://inlzqy4v3qyo0wagcmilgnxpry-byoc-nuon-install-templates.s3.eu-west-1.amazonaws.com/templates/runner-sg-eks-access.yaml"
index        = 0

[custom_nested_stacks.parameters]
ClusterName = "{{.nuon.install.inputs.cluster_name}}"

[[custom_nested_stacks]]
name         = "k8s_namespaces"
template_url = "https://inlzqy4v3qyo0wagcmilgnxpry-byoc-nuon-install-templates.s3.eu-west-1.amazonaws.com/templates/k8s-namespaces.yaml"
index        = 1

[custom_nested_stacks.parameters]
Namespaces  = "{{.nuon.install.inputs.namespace}}"
ClusterName = "{{.nuon.install.inputs.cluster_name}}"

[[custom_nested_stacks]]
name         = "eks_access_entries"
template_url = "https://inlzqy4v3qyo0wagcmilgnxpry-byoc-nuon-install-templates.s3.eu-west-1.amazonaws.com/templates/runner-eks-access-entries.yaml"
index        = 2

[custom_nested_stacks.parameters]
Namespaces  = "{{.nuon.install.inputs.namespace}}"
ClusterName = "{{.nuon.install.inputs.cluster_name}}"
