type      = "kubernetes_manifest"
name      = "namespace"
namespace = "{{.nuon.install.inputs.namespace}}"

max_auto_retries = 5

manifest = """
apiVersion: v1
kind: Namespace
metadata:
  name: {{.nuon.install.inputs.namespace}}
  labels:
    install.nuon.co/id: "{{.nuon.install.id}}"
"""
