type         = "deprovision"
name         = "{{.nuon.install.id}}-deprovision"
description  = "deprovision the sandbox and components"
display_name = "deprovision role"

[[policies]]
managed_policy_name = "AdministratorAccess"
